model = "gpt-5-codex"
model_reasoning_effort = "high"

[projects."/home/prei/jianing"]
trust_level = "trusted"

[projects."/home/prei/jianing/test-pydoll"]
trust_level = "trusted"

[projects."/home/prei/zhongwen-video"]
trust_level = "trusted"

[projects."/home/prei/retirers/microsaas-boilerplate"]
trust_level = "trusted"

[projects."/home/prei/dotfiles"]
trust_level = "trusted"

[projects."/home/prei"]
trust_level = "trusted"

[projects."/home/prei/jianing/new-code"]
trust_level = "trusted"

[mcp_servers.serena]
command = "uvx"
args = ["--from", "git+https://github.com/oraios/serena", "serena", "start-mcp-server", "--context", "codex"]

[mcp_servers.context7]
args = ["-y", "@upstash/context7-mcp", "--api-key", "ctx7sk-f2c54c89-d1b8-4c57-ae2b-0dbd24a9072b"]
command = "npx"

# Repomix MCP (stdio)
[mcp_servers.repomix]
command = "npx"
args    = ["-y", "repomix", "--mcp"]
# optional: give slower machines more time to start
startup_timeout_ms = 20000

[mcp_servers.playwright]
command = "npx"
args = ["@playwright/mcp@latest"]

[mcp_server.chrome-devtools]
command = "npx"
args = ["chrome-dev-tools-mcp@latest"]


[tui]
# Send desktop notifications when approvals are required or a turn completes.
# Defaults to false.
notifications = true

[tools]
web_search = true
