import concurrent.futures
import io
import os
import re
import shutil
import tarfile
import tempfile
import urllib.request
from pathlib import Path

BASE = "https://docs.stencil.so/tern/"
REFERENCES = Path(__file__).resolve().parent.parent / "references"
DOCS_DIR = REFERENCES / "docs"
SDK_DIR = REFERENCES / "sdk"
TOC_FILE = REFERENCES / "toc.md"
TOC_ENTRY = re.compile(r'<li class="part-title">([^<]+)</li>|<a href="([^"#]+)\.html">([^<]+)</a>')
TOC_HREF = re.compile(r'href="([^"#]+)\.html')


def get(url: str) -> tuple[str, bytes]:
    request = urllib.request.Request(url, headers={"User-Agent": "Mozilla/5.0"})
    with urllib.request.urlopen(request, timeout=60) as response:
        return response.headers.get("content-type", ""), response.read()


def read_toc() -> list[tuple[str, str, str]]:
    _, index_html = get(BASE + "index.html")
    toc_script = re.search(r'src="(toc-[^"]+\.js)"', index_html.decode()).group(1)
    _, toc_js = get(BASE + toc_script)
    toc = toc_js.decode().replace('\\"', '"')
    entries: list[tuple[str, str, str]] = []
    seen: set[str] = set()
    part = "Overview"
    for match in TOC_ENTRY.finditer(toc):
        if match.group(1):
            part = match.group(1)
            continue
        if match.group(2) not in seen:
            seen.add(match.group(2))
            entries.append((part, match.group(2) + ".md", match.group(3)))
    linked = set(TOC_HREF.findall(toc))
    if not entries or seen != linked:
        raise RuntimeError(f"TOC_ENTRY matched {len(seen)} of {len(linked)} TOC links; update the pattern")
    return entries


def fetch_page(path: str) -> str:
    content_type, body = get(BASE + path)
    if "markdown" not in content_type:
        raise RuntimeError(f"{path}: expected markdown, got {content_type}")
    return body.decode()


def section_headings(markdown: str) -> list[str]:
    headings: list[str] = []
    in_fence = False
    for line in markdown.splitlines():
        if line.startswith(("```", "~~~")):
            in_fence = not in_fence
        elif not in_fence and line.startswith("## "):
            headings.append(line[3:].strip())
    return headings


def render_toc(entries: list[tuple[str, str, str]], pages: dict[str, str]) -> str:
    lines = [f"# Tern plugin SDK docs ({BASE})", "", "Generated by `scripts/sync_docs.py`. Paths are relative to `references/docs/`."]
    current_part = ""
    for part, path, title in entries:
        if part != current_part:
            lines += ["", f"## {part}", ""]
            current_part = part
        headings = "; ".join(section_headings(pages[path]))
        lines.append(f"- [{title}](docs/{path}): {headings}")
    return "\n".join(lines) + "\n"


def extract_sdk(archive: bytes, destination: Path) -> None:
    with tarfile.open(fileobj=io.BytesIO(archive), mode="r:gz") as tar:
        members = []
        for member in tar.getmembers():
            name = member.name.removeprefix("./")
            if name == "tern-sdk":
                continue
            if not name.startswith("tern-sdk/"):
                raise RuntimeError(f"unexpected SDK archive member {member.name}")
            member.name = name.removeprefix("tern-sdk/")
            members.append(member)
        tar.extractall(destination, members=members, filter="data")


def main() -> None:
    entries = read_toc()
    paths = [path for _, path, _ in entries]
    with concurrent.futures.ThreadPoolExecutor(16) as pool:
        pages = dict(zip(paths, pool.map(fetch_page, paths)))
    _, sdk_archive = get(BASE + "tern-sdk.tar.gz")

    with tempfile.TemporaryDirectory(dir=REFERENCES) as staging_dir:
        staging = Path(staging_dir)
        for path, body in pages.items():
            target = staging / "docs" / path
            target.parent.mkdir(parents=True, exist_ok=True)
            target.write_text(body, encoding="utf-8")
        extract_sdk(sdk_archive, staging / "sdk")
        (staging / "toc.md").write_text(render_toc(entries, pages), encoding="utf-8")
        for current in (DOCS_DIR, SDK_DIR):
            if current.exists():
                shutil.rmtree(current)
            os.replace(staging / current.name, current)
        os.replace(staging / "toc.md", TOC_FILE)
    print(f"{len(pages)} pages -> {DOCS_DIR}, SDK -> {SDK_DIR}, index -> {TOC_FILE}")


if __name__ == "__main__":
    main()
