set -g default-terminal "xterm-256color"

# Remap super
unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

# Bind splits to - and =
bind - split-window -h
bind = split-window -v
unbind %

# Bind kill window without confirmation
bind & kill-window

# Vi key mappings
set-window-option -g mode-keys vi

# reload config file (change file location to your the tmux.conf you want to use)
bind r source-file ~/.tmux.conf

# List of plugins
set -g @plugin "tmux-plugins/tpm"
set -g @plugin "tmux-plugins/tmux-sensible"
set -g @plugin "tmux-plugins/tmux-resurrect"
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin "dracula/tmux"
set -g @plugin 'tmux-plugins/tmux-yank'

# Dracula
set -g @dracula-show-powerline true
set -g @dracula-show-left-icon session
set -g @dracula-border-contrast true
set -g @dracula-plugins "cpu-usage ram-usage"

# Other examples:
# set -g @plugin "github_username/plugin_name"
# set -g @plugin "github_username/plugin_name#branch"
# set -g @plugin "git@github.com:user/plugin"
# set -g @plugin "git@bitbucket.com:user/plugin"

# Sane scrolling 
set -g terminal-overrides 'xterm*:smcup@:rmcup@'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run "~/.tmux/plugins/tpm/tpm"

