providers: 
  webSearch: auto
symbolPreset: nerd
theme: 
  dark: titanium
  light: light
setupVersion: 1
modelRoles: 
  advisor: anthropic/claude-opus-5:medium
  default: anthropic/claude-sonnet-5:max
  commit: zai/glm-5-turbo
  smol: anthropic/claude-haiku-4-5:minimal
  tiny: anthropic/claude-haiku-4-5:minimal
  task: anthropic/claude-sonnet-5:max
  slow: anthropic/claude-opus-5:medium
defaultThinkingLevel: auto
task: 
  eager: always
  disabledAgents: 
    - designer
    - librarian
    - plan
    - reviewer
    - scout
    - sonic
  agentModelOverrides: 
    adversary: zai/glm-5.2:xhigh
    enemy: anthropic/claude-opus-5:medium
    explorer: anthropic/claude-opus-5:medium
    git-commit-specialist: zai/glm-5-turbo
    planner: anthropic/claude-opus-5:medium
    technical-architect: anthropic/claude-opus-5:medium
    surveyor: zai/glm-5.2:xhigh
    strategist: zai/glm-5.2:xhigh
    triage: anthropic/claude-haiku-4-5:minimal
    task: anthropic/claude-sonnet-5:max
dev: 
  autoqa: 
    consent: granted